package com.puj.admincenter.dto.concepts

data class ConceptsDto(
    val idHybrid: String?,
    val pxordx: String,
    val oldpxordx: String?,
    val codetype: String,
    val conceptClassId:  String?,
    val conceptId: Int,
    val vocabularyId:  String,
    val domainId: String,
    val track:  String?,
    val standardConcept: String?,
    val code: String,
    val codewithperiods:  String?,
    val codescheme:  String?,
    val longDesc:  String?,
    val shortDesc:  String?,
    val codeStatus:  String?,
    val codeChange:  String?,
    val codeChangeYear:  String?,
    val codePlannedType:  String?,
    val codeBillingStatus:  String?,
    val codeCmsClaimStatus:  String?,
    val sexCd:  String?,
    val anatOrCond:  String?,
    val poaCodeStatus:  String?,
    val poaCodeChange:  String?,
    val poaCodeChangeYear:  String?,
    val validStartDate:  String?,
    val validEndDate:  String?,
    val invalidReason:  String?,
    val createDt: Int?,
    val conceptState: Int
)